### ISSUE TITLE
Update License to MPL2?

### ISSUE THREAD

**Issue by chorrell** [joyent/gomanta#5]
The license for this should probably be changed to MPL2

**Comment by misterbisson** [comment]
Yes, in keeping with https://github.com/joyent/gosdc/issues/11 and https://github.com/joyent/gocommon/issues/6, this should also be MPLv2. Tasks:

1. Review for any dependencies that may be incompatible with MPLv2, remove them
  - If changes are required there, they might break consumers
1. Replace the license file and other references to the existing license with references to MPLv2.
